export const alphabet = [
    { letter: "ހ", name: "ހާ", word: "ހަނދު", audio: "haa.mp3", wordAudio: "handhu.mp3" },
    { letter: "ށ", name: "ށަވިޔަނި", word: "ށަވިޔަނި", audio: "shaviyani.mp3", wordAudio: "sharubathu.mp3" },
    { letter: "ނ", name: "ނޫނު", word: "ނާށި", audio: "noonu.mp3", wordAudio: "naashi.mp3" },
    { letter: "ރ", name: "ރާ", word: "ރަށް", audio: "raa.mp3", wordAudio: "rah.mp3" },
    { letter: "ބ", name: "ބާ", word: "ބޯޅަ", audio: "baa.mp3", wordAudio: "bolha.mp3" },
    { letter: "ޅ", name: "ޅަވިޔަނި", word: "ޅަނދަރު", audio: "lhaviyani.mp3", wordAudio: "lhandharu.mp3" },
    { letter: "ކ", name: "ކާފު", word: "ކޮކާ", audio: "kaafu.mp3", wordAudio: "koka.mp3" },
    { letter: "އ", name: "އަލިފު", word: "އިރު", audio: "alifu.mp3", wordAudio: "iru.mp3" },
    { letter: "ވ", name: "ވާވު", word: "ވަލު", audio: "vaavu.mp3", wordAudio: "valu.mp3" },
    { letter: "މ", name: "މީމު", word: "މާ", audio: "meemu.mp3", wordAudio: "maa.mp3" },
    { letter: "ފ", name: "ފާފު", word: "ފަތް", audio: "faafu.mp3", wordAudio: "fath.mp3" },
    { letter: "ދ", name: "ދާލު", word: "ދޫނި", audio: "dhaalu.mp3", wordAudio: "dooni.mp3" },
    { letter: "ތ", name: "ތާ", word: "ތަރި", audio: "thaa.mp3", wordAudio: "thari.mp3" },
    { letter: "ލ", name: "ލާމު", word: "ލުނބޯ", audio: "laamu.mp3", wordAudio: "lunbo.mp3" },
    { letter: "ގ", name: "ގާފު", word: "ގަސް", audio: "gaafu.mp3", wordAudio: "gas.mp3" },
    { letter: "ޏ", name: "ޏަވިޔަނި", word: "ޏަމްޏަމް", audio: "gnaviyani.mp3", wordAudio: "nyamnyam.mp3" },
    { letter: "ސ", name: "ސީނު", word: "ސައި", audio: "seenu.mp3", wordAudio: "sai.mp3" },
    { letter: "ޑ", name: "ޑަވިޔަނި", word: "ޑަބިޔާ", audio: "daviyani.mp3", wordAudio: "dabiya.mp3" },
    { letter: "ޒ", name: "ޒަވިޔަނި", word: "ޒީބްރާ", audio: "zaviyani.mp3", wordAudio: "zebra.mp3" },
    { letter: "ޓ", name: "ޓަވިޔަނި", word: "ޓީވީ", audio: "taviyani.mp3", wordAudio: "tv.mp3" },
    { letter: "ޔ", name: "ޔާ", word: "ޔާގޫތު", audio: "yaayu.mp3", wordAudio: "yaguth.mp3" },
    { letter: "ޕ", name: "ޕަވިޔަނި", word: "ޕާން", audio: "paviyani.mp3", wordAudio: "paan.mp3" },
    { letter: "ޖ", name: "ޖަވިޔަނި", word: "ޖޯޑު", audio: "javiyani.mp3", wordAudio: "jodu.mp3" },
    { letter: "ޗ", name: "ޗަވިޔަނި", word: "ޗަސް", audio: "chaviyani.mp3", wordAudio: "chas.mp3" }
];
