const content = {
    dhivehi: [
        { letter: "ހ", name: "ހާ", word: "ހަނދު", english: "Moon", audio: "haa.mp3", wordAudio: "handhu.mp3" },
        { letter: "ށ", name: "ށަވިޔަނި", word: "ށަވިޔަނި", english: "Sherbet", audio: "shaviyani.mp3", wordAudio: "sharubathu.mp3" },
        { letter: "ނ", name: "ނޫނު", word: "ނާށި", english: "Coconut Shell", audio: "noonu.mp3", wordAudio: "naashi.mp3" },
        { letter: "ރ", name: "ރާ", word: "ރަށް", english: "Island", audio: "raa.mp3", wordAudio: "rah.mp3" },
        { letter: "ބ", name: "ބާ", word: "ބޯޅަ", english: "Ball", audio: "baa.mp3", wordAudio: "bolha.mp3" },
        { letter: "ޅ", name: "ޅަވިޔަނި", word: "ޅަނދަރު", english: "Calf", audio: "lhaviyani.mp3", wordAudio: "lhandharu.mp3" },
        { letter: "ކ", name: "ކާފު", word: "ކޮކާ", english: "Butterfly", audio: "kaafu.mp3", wordAudio: "koka.mp3" },
        { letter: "އ", name: "އަލިފު", word: "އިރު", english: "Sun", audio: "alifu.mp3", wordAudio: "iru.mp3" },
        { letter: "ވ", name: "ވާވު", word: "ވަލު", english: "Forest", audio: "vaavu.mp3", wordAudio: "valu.mp3" },
        { letter: "މ", name: "މީމު", word: "މާ", english: "Flower", audio: "meemu.mp3", wordAudio: "maa.mp3" },
        { letter: "ފ", name: "ފާފު", word: "ފަތް", english: "Leaf", audio: "faafu.mp3", wordAudio: "fath.mp3" },
        { letter: "ދ", name: "ދާލު", word: "ދޫނި", english: "Bird", audio: "dhaalu.mp3", wordAudio: "dooni.mp3" },
        { letter: "ތ", name: "ތާ", word: "ތަރި", english: "Star", audio: "thaa.mp3", wordAudio: "thari.mp3" },
        { letter: "ލ", name: "ލާމު", word: "ލުނބޯ", english: "Lemon", audio: "laamu.mp3", wordAudio: "lunbo.mp3" },
        { letter: "ގ", name: "ގާފު", word: "ގަސް", english: "Tree", audio: "gaafu.mp3", wordAudio: "gas.mp3" },
        { letter: "ޏ", name: "ޏަވިޔަނި", word: "ޏަމްޏަމް", english: "Namnam", audio: "gnaviyani.mp3", wordAudio: "nyamnyam.mp3" },
        { letter: "ސ", name: "ސީނު", word: "ސައި", english: "Tea", audio: "seenu.mp3", wordAudio: "sai.mp3" },
        { letter: "ޑ", name: "ޑަވިޔަނި", word: "ޑަބިޔާ", english: "Can", audio: "daviyani.mp3", wordAudio: "dabiya.mp3" },
        { letter: "ޒ", name: "ޒަވިޔަނި", word: "ޒީބްރާ", english: "Zebra", audio: "zaviyani.mp3", wordAudio: "zebra.mp3" },
        { letter: "ޓ", name: "ޓަވިޔަނި", word: "ޓީވީ", english: "TV", audio: "taviyani.mp3", wordAudio: "tv.mp3" },
        { letter: "ޔ", name: "ޔާޔޫ", word: "ޔާގޫތު", english: "Ruby", audio: "yaayu.mp3", wordAudio: "yaguth.mp3" },
        { letter: "ޕ", name: "ޕަވިޔަނި", word: "ޕާން", english: "Bread", audio: "paviyani.mp3", wordAudio: "paan.mp3" },
        { letter: "ޖ", name: "ޖަވިޔަނި", word: "ޖޯޑު", english: "Pair", audio: "javiyani.mp3", wordAudio: "jodu.mp3" },
        { letter: "ޗ", name: "ޗަވިޔަނި", word: "ޗަސް", english: "Crush", audio: "chaviyani.mp3", wordAudio: "chas.mp3" }
    ],
    english: [
        { letter: "A", name: "A", word: "Apple", english: "Apple", audio: "en_a.mp3", wordAudio: "en_apple.mp3" },
        { letter: "B", name: "B", word: "Ball", english: "Ball", audio: "en_b.mp3", wordAudio: "en_ball.mp3" },
        { letter: "C", name: "C", word: "Cat", english: "Cat", audio: "en_c.mp3", wordAudio: "en_cat.mp3" },
        { letter: "D", name: "D", word: "Dog", english: "Dog", audio: "en_d.mp3", wordAudio: "en_dog.mp3" },
        { letter: "E", name: "E", word: "Elephant", english: "Elephant", audio: "en_e.mp3", wordAudio: "en_elephant.mp3" },
        { letter: "F", name: "F", word: "Fish", english: "Fish", audio: "en_f.mp3", wordAudio: "en_fish.mp3" },
        { letter: "G", name: "G", word: "Giraffe", english: "Giraffe", audio: "en_g.mp3", wordAudio: "en_giraffe.mp3" },
        { letter: "H", name: "H", word: "Horse", english: "Horse", audio: "en_h.mp3", wordAudio: "en_horse.mp3" },
        { letter: "I", name: "I", word: "Igloo", english: "Igloo", audio: "en_i.mp3", wordAudio: "en_igloo.mp3" },
        { letter: "J", name: "J", word: "Jelly", english: "Jelly", audio: "en_j.mp3", wordAudio: "en_jelly.mp3" },
        { letter: "K", name: "K", word: "Kite", english: "Kite", audio: "en_k.mp3", wordAudio: "en_kite.mp3" },
        { letter: "L", name: "L", word: "Lion", english: "Lion", audio: "en_l.mp3", wordAudio: "en_lion.mp3" },
        { letter: "M", name: "M", word: "Monkey", english: "Monkey", audio: "en_m.mp3", wordAudio: "en_monkey.mp3" },
        { letter: "N", name: "N", word: "Net", english: "Net", audio: "en_n.mp3", wordAudio: "en_net.mp3" },
        { letter: "O", name: "O", word: "Orange", english: "Orange", audio: "en_o.mp3", wordAudio: "en_orange.mp3" },
        { letter: "P", name: "P", word: "Panda", english: "Panda", audio: "en_p.mp3", wordAudio: "en_panda.mp3" },
        { letter: "Q", name: "Q", word: "Queen", english: "Queen", audio: "en_q.mp3", wordAudio: "en_queen.mp3" },
        { letter: "R", name: "R", word: "Rabbit", english: "Rabbit", audio: "en_r.mp3", wordAudio: "en_rabbit.mp3" },
        { letter: "S", name: "S", word: "Sun", english: "Sun", audio: "en_s.mp3", wordAudio: "en_sun.mp3" },
        { letter: "T", name: "T", word: "Tiger", english: "Tiger", audio: "en_t.mp3", wordAudio: "en_tiger.mp3" },
        { letter: "U", name: "U", word: "Umbrella", english: "Umbrella", audio: "en_u.mp3", wordAudio: "en_umbrella.mp3" },
        { letter: "V", name: "V", word: "Van", english: "Van", audio: "en_v.mp3", wordAudio: "en_van.mp3" },
        { letter: "W", name: "W", word: "Whale", english: "Whale", audio: "en_w.mp3", wordAudio: "en_whale.mp3" },
        { letter: "X", name: "X", word: "Xylophone", english: "Xylophone", audio: "en_x.mp3", wordAudio: "en_xylophone.mp3" },
        { letter: "Y", name: "Y", word: "Yo-yo", english: "Yo-yo", audio: "en_y.mp3", wordAudio: "en_yoyo.mp3" },
        { letter: "Z", name: "Z", word: "Zebra", english: "Zebra", audio: "en_z.mp3", wordAudio: "en_zebra.mp3" }
    ],
    arabic: [
        { letter: "أ", name: "Alif", word: "أرنب", audio: "ar_alif.mp3", wordAudio: "ar_arnab.mp3" },
        { letter: "ب", name: "Ba", word: "بطة", audio: "ar_ba.mp3", wordAudio: "ar_batta.mp3" },
        { letter: "ت", name: "Ta", word: "تفاح", audio: "ar_ta.mp3", wordAudio: "ar_tuffah.mp3" },
        { letter: "ث", name: "Tha", word: "ثعلب", audio: "ar_tha.mp3", wordAudio: "ar_thalab.mp3" },
        { letter: "ج", name: "Jim", word: "جمل", audio: "ar_jim.mp3", wordAudio: "ar_jamal.mp3" },
        { letter: "ح", name: "Ha", word: "حوت", audio: "ar_ha.mp3", wordAudio: "ar_hoot.mp3" },
        { letter: "خ", name: "Kha", word: "خروف", audio: "ar_kha.mp3", wordAudio: "ar_kharoof.mp3" },
        { letter: "د", name: "Dal", word: "دب", audio: "ar_dal.mp3", wordAudio: "ar_dub.mp3" },
        { letter: "ذ", name: "Thal", word: "ذئب", audio: "ar_thal.mp3", wordAudio: "ar_theeb.mp3" },
        { letter: "ر", name: "Ra", word: "رمان", audio: "ar_ra.mp3", wordAudio: "ar_ruman.mp3" },
        { letter: "ز", name: "Zay", word: "زرافة", audio: "ar_zay.mp3", wordAudio: "ar_zarafa.mp3" },
        { letter: "س", name: "Sin", word: "سمكة", audio: "ar_sin.mp3", wordAudio: "ar_samaka.mp3" },
        { letter: "ش", name: "Shin", word: "شمس", audio: "ar_shin.mp3", wordAudio: "ar_shams.mp3" },
        { letter: "ص", name: "Sad", word: "صقر", audio: "ar_sad.mp3", wordAudio: "ar_saqr.mp3" },
        { letter: "ض", name: "Dad", word: "ضفدع", audio: "ar_dad.mp3", wordAudio: "ar_difda.mp3" },
        { letter: "ط", name: "Ta", word: "طائرة", audio: "ar_ta_heavy.mp3", wordAudio: "ar_taira.mp3" },
        { letter: "ظ", name: "Za", word: "ظرف", audio: "ar_za_heavy.mp3", wordAudio: "ar_zarf.mp3" },
        { letter: "ع", name: "Ain", word: "عين", audio: "ar_ain.mp3", wordAudio: "ar_ain_word.mp3" },
        { letter: "غ", name: "Ghain", word: "غزال", audio: "ar_ghain.mp3", wordAudio: "ar_ghazal.mp3" },
        { letter: "ف", name: "Fa", word: "فيل", audio: "ar_fa.mp3", wordAudio: "ar_feel.mp3" },
        { letter: "ق", name: "Qaf", word: "قرد", audio: "ar_qaf.mp3", wordAudio: "ar_qird.mp3" },
        { letter: "ك", name: "Kaf", word: "كلب", audio: "ar_kaf.mp3", wordAudio: "ar_kalb.mp3" },
        { letter: "ل", name: "Lam", word: "ليمون", audio: "ar_lam.mp3", wordAudio: "ar_laymoon.mp3" },
        { letter: "م", name: "Mim", word: "موز", audio: "ar_mim.mp3", wordAudio: "ar_moaz.mp3" },
        { letter: "ن", name: "Nun", word: "نحلة", audio: "ar_nun.mp3", wordAudio: "ar_nahla.mp3" },
        { letter: "ه", name: "Ha", word: "هلال", audio: "ar_ha_light.mp3", wordAudio: "ar_hilal.mp3" },
        { letter: "و", name: "Waw", word: "وردة", audio: "ar_waw.mp3", wordAudio: "ar_warda.mp3" },
        { letter: "ي", name: "Ya", word: "يد", audio: "ar_ya.mp3", wordAudio: "ar_yad.mp3" }
    ],
    engdhi: [
        { letter: "A", english: "Apple", dhivehi: "އާފަލު", audio: "en_a.mp3" },
        { letter: "B", english: "Ball", dhivehi: "ބޯޅަ", audio: "en_b.mp3" },
        { letter: "C", english: "Cat", dhivehi: "ބުޅާ", audio: "en_c.mp3" },
        { letter: "D", english: "Dog", dhivehi: "ކުއްތާ", audio: "en_d.mp3" },
        { letter: "E", english: "Elephant", dhivehi: "އެތް", audio: "en_e.mp3" },
        { letter: "F", english: "Fish", dhivehi: "މަސް", audio: "en_f.mp3" },
        { letter: "G", english: "Giraffe", dhivehi: "ޒަރާފާ", audio: "en_g.mp3" },
        { letter: "H", english: "Horse", dhivehi: "އަސް", audio: "en_h.mp3" },
        { letter: "I", english: "Igloo", dhivehi: "އިގްލޫ", audio: "en_i.mp3" },
        { letter: "J", english: "Jelly", dhivehi: "ޖެލީ", audio: "en_j.mp3" },
        { letter: "K", english: "Kite", dhivehi: "ވަައިގުޑި", audio: "en_k.mp3" },
        { letter: "L", english: "Lion", dhivehi: "ސިންގާ", audio: "en_l.mp3" },
        { letter: "M", english: "Monkey", dhivehi: "ރިލް", audio: "en_m.mp3" },
        { letter: "N", english: "Net", dhivehi: "ދާ", audio: "en_n.mp3" },
        { letter: "O", english: "Orange", dhivehi: "އޮރެންޖް", audio: "en_o.mp3" },
        { letter: "P", english: "Panda", dhivehi: "ޕަންޑާ", audio: "en_p.mp3" },
        { letter: "Q", english: "Queen", dhivehi: "ރަނިކަމަނާ", audio: "en_q.mp3" },
        { letter: "R", english: "Rabbit", dhivehi: "މުސަޅު", audio: "en_r.mp3" },
        { letter: "S", english: "Sun", dhivehi: "އިރު", audio: "en_s.mp3" },
        { letter: "T", english: "Tiger", dhivehi: "މިނިކާވަގު", audio: "en_t.mp3" }
    ]
};

const filiData = [
    { mark: "ަ", name: "އަބަފިލި", audio: "abafili.mp3" },
    { mark: "ި", name: "އިބިފިލި", audio: "ibifili.mp3" },
    { mark: "ު", name: "އުބުފިލި", audio: "ubufili.mp3" },
    { mark: "ާ", name: "އާފިލި", audio: "aafili.mp3" },
    { mark: "ީ", name: "އީފިލި", audio: "eefili.mp3" },
    { mark: "ޫ", name: "އޫފިލި", audio: "oofili.mp3" },
    { mark: "ެ", name: "އެބެފިލި", audio: "ebefili.mp3" },
    { mark: "ޭ", name: "އޭފިލި", audio: "eefili_long.mp3" },
    { mark: "ޮ", name: "އޮބޮފިލި", audio: "obofili.mp3" },
    { mark: "ޯ", name: "އޯފިލި", audio: "oofili_long.mp3" },
    { mark: "ް", name: "ސުކުން", audio: "sukun.mp3" }
];

const badges = [
    { id: 1, name: "First Step", icon: "🌱" },
    { id: 2, name: "Tracer Pro", icon: "✏️" },
    { id: 3, name: "Quiz Master", icon: "⭐" },
    { id: 4, name: "Word Explorer", icon: "🖼️" },
    { id: 5, name: "Dhivehi Fan", icon: "🇲🇻" },
    { id: 6, name: "English Scholar", icon: "🇬🇧" },
    { id: 7, name: "Arabic Learner", icon: "🇸🇦" },
    { id: 8, name: "Early Bird", icon: "🌅" },
    { id: 9, name: "Night Owl", icon: "🦉" },
    { id: 10, name: "Speedy Tracer", icon: "🏎️" },
    { id: 11, name: "Perfect Quiz", icon: "💯" },
    { id: 12, name: "Coloring Artist", icon: "🎨" },
    { id: 13, name: "Fili Expert", icon: "✨" },
    { id: 14, name: "Object Hunter", icon: "🔍" },
    { id: 15, name: "Mystery Solver", icon: "🎁" },
    { id: 16, name: "Super Student", icon: "👔" },
    { id: 17, name: "Happy Learner", icon: "😊" },
    { id: 18, name: "Knowledge King", icon: "👑" },
    { id: 19, name: "Alphabet Hero", icon: "🦸" },
    { id: 20, name: "Brave Writer", icon: "🗡️" },
    { id: 21, name: "Silver Medal", icon: "🥈" },
    { id: 22, name: "Gold Medal", icon: "🥇" },
    { id: 23, name: "Diamond Badge", icon: "💎" },
    { id: 24, name: "Rocket Learner", icon: "🚀" },
    { id: 25, name: "Brain Power", icon: "🧠" },
    { id: 26, name: "Daily Hero", icon: "📅" },
    { id: 27, name: "Star Student", icon: "🌟" },
    { id: 28, name: "Magic Writer", icon: "🪄" },
    { id: 29, name: "Friend of Letters", icon: "🤝" },
    { id: 30, name: "Voice of Hub", icon: "📣" },
    { id: 31, name: "Smart Cookie", icon: "🍪" },
    { id: 32, name: "Focus Finder", icon: "🎯" },
    { id: 33, name: "Explorer Badge", icon: "🧭" },
    { id: 34, name: "Winner Spirit", icon: "🏆" },
    { id: 35, name: "Kind Heart", icon: "❤️" },
    { id: 36, name: "Fire Starter", icon: "🔥" },
    { id: 37, name: "Ice Cooler", icon: "❄️" },
    { id: 38, name: "Sun Shiner", icon: "☀️" },
    { id: 39, name: "Cloud Walker", icon: "☁️" },
    { id: 40, name: "Rainbow Maker", icon: "🌈" },
    { id: 41, name: "Globe Trotter", icon: "🌍" },
    { id: 42, name: "Music Lover", icon: "🎵" },
    { id: 43, name: "Book Worm", icon: "📖" },
    { id: 44, name: "Idea Spark", icon: "💡" },
    { id: 45, name: "Team Player", icon: "👨‍👩‍👧‍👦" },
    { id: 46, name: "Peace Maker", icon: "🕊️" },
    { id: 47, name: "Growth Mindset", icon: "📈" },
    { id: 48, name: "Infinite Wisdom", icon: "♾️" },
    { id: 49, name: "Grand Champion", icon: "🏅" },
    { id: 50, name: "Ultimate Legend", icon: "🦄" }
];
