const content = {
    dhivehi: [
        { letter: "ހ", name: "ހާ", word: "ހަނދު", english: "Moon", audio: "haa.mp3", word_audio: "handhu.mp3" },
        { letter: "ށ", name: "ށަވިޔަނި", word: "ށަވިޔަނި", english: "Sherbet", audio: "shaviyani.mp3", word_audio: "sharubathu.mp3" },
        { letter: "ނ", name: "ނޫނު", word: "ނާށި", english: "Coconut Shell", audio: "noonu.mp3", word_audio: "naashi.mp3" },
        { letter: "ރ", name: "ރާ", word: "ރަށް", english: "Island", audio: "raa.mp3", word_audio: "rah.mp3" },
        { letter: "ބ", name: "ބާ", word: "ބޯޅަ", english: "Ball", audio: "baa.mp3", word_audio: "bolha.mp3" },
        { letter: "ޅ", name: "ޅަވިޔަނި", word: "ޅަނދަރު", english: "Calf", audio: "lhaviyani.mp3", word_audio: "lhandharu.mp3" },
        { letter: "ކ", name: "ކާފު", word: "ކޮކާ", english: "Butterfly", audio: "kaafu.mp3", word_audio: "koka.mp3" },
        { letter: "އ", name: "އަލިފު", word: "އިރު", english: "Sun", audio: "alifu.mp3", word_audio: "iru.mp3" },
        { letter: "ވ", name: "ވާވު", word: "ވަލު", english: "Forest", audio: "vaavu.mp3", word_audio: "valu.mp3" },
        { letter: "މ", name: "މީމު", word: "މާ", english: "Flower", audio: "meemu.mp3", word_audio: "maa.mp3" },
        { letter: "ފ", name: "ފާފު", word: "ފަތް", english: "Leaf", audio: "faafu.mp3", word_audio: "fath.mp3" },
        { letter: "ދ", name: "ދާލު", word: "ދޫނި", english: "Bird", audio: "dhaalu.mp3", word_audio: "dooni.mp3" },
        { letter: "ތ", name: "ތާ", word: "ތަރި", english: "Star", audio: "thaa.mp3", word_audio: "thari.mp3" },
        { letter: "ލ", name: "ލާމު", word: "ލުނބޯ", english: "Lemon", audio: "laamu.mp3", word_audio: "lunbo.mp3" },
        { letter: "ގ", name: "ގާފު", word: "ގަސް", english: "Tree", audio: "gaafu.mp3", word_audio: "gas.mp3" },
        { letter: "ޏ", name: "ޏަވިޔަނި", word: "ޏަމްޏަމް", english: "Namnam", audio: "gnaviyani.mp3", word_audio: "nyamnyam.mp3" },
        { letter: "ސ", name: "ސީނު", word: "ސައި", english: "Tea", audio: "seenu.mp3", word_audio: "sai.mp3" },
        { letter: "ޑ", name: "ޑަވިޔަނި", word: "ޑަބިޔާ", english: "Can", audio: "daviyani.mp3", word_audio: "dabiya.mp3" },
        { letter: "ޒ", name: "ޒަވިޔަނި", word: "ޒީބްރާ", english: "Zebra", audio: "zaviyani.mp3", word_audio: "zebra.mp3" },
        { letter: "ޓ", name: "ޓަވިޔަނި", word: "ޓީވީ", english: "TV", audio: "taviyani.mp3", word_audio: "tv.mp3" },
        { letter: "ޔ", name: "ޔާޔޫ", word: "ޔާގޫތު", english: "Ruby", audio: "yaayu.mp3", word_audio: "yaguth.mp3" },
        { letter: "ޕ", name: "ޕަވިޔަނި", word: "ޕާން", english: "Bread", audio: "paviyani.mp3", word_audio: "paan.mp3" },
        { letter: "ޖ", name: "ޖަވިޔަނި", word: "ޖޯޑު", english: "Pair", audio: "javiyani.mp3", word_audio: "jodu.mp3" },
        { letter: "ޗ", name: "ޗަވިޔަނި", word: "ޗަސް", english: "Crush", audio: "chaviyani.mp3", word_audio: "chas.mp3" }
    ],
    english: [
        { letter: "A", name: "A", word: "Apple", english: "Apple", audio: "en_a.mp3", word_audio: "en_apple.mp3" },
        { letter: "B", name: "B", word: "Ball", english: "Ball", audio: "en_b.mp3", word_audio: "en_ball.mp3" },
        { letter: "C", name: "C", word: "Cat", english: "Cat", audio: "en_c.mp3", word_audio: "en_cat.mp3" },
        { letter: "D", name: "D", word: "Dog", english: "Dog", audio: "en_d.mp3", word_audio: "en_dog.mp3" },
        { letter: "E", name: "E", word: "Elephant", english: "Elephant", audio: "en_e.mp3", word_audio: "en_elephant.mp3" },
        { letter: "F", name: "F", word: "Fish", english: "Fish", audio: "en_f.mp3", word_audio: "en_fish.mp3" },
        { letter: "G", name: "G", word: "Giraffe", english: "Giraffe", audio: "en_g.mp3", word_audio: "en_giraffe.mp3" },
        { letter: "H", name: "H", word: "Horse", english: "Horse", audio: "en_h.mp3", word_audio: "en_horse.mp3" },
        { letter: "I", name: "I", word: "Igloo", english: "Igloo", audio: "en_i.mp3", word_audio: "en_igloo.mp3" },
        { letter: "J", name: "J", word: "Jelly", english: "Jelly", audio: "en_j.mp3", word_audio: "en_jelly.mp3" },
        { letter: "K", name: "K", word: "Kite", english: "Kite", audio: "en_k.mp3", word_audio: "en_kite.mp3" },
        { letter: "L", name: "L", word: "Lion", english: "Lion", audio: "en_l.mp3", word_audio: "en_lion.mp3" },
        { letter: "M", name: "M", word: "Monkey", english: "Monkey", audio: "en_m.mp3", word_audio: "en_monkey.mp3" },
        { letter: "N", name: "N", word: "Net", english: "Net", audio: "en_n.mp3", word_audio: "en_net.mp3" },
        { letter: "O", name: "O", word: "Orange", english: "Orange", audio: "en_o.mp3", word_audio: "en_orange.mp3" },
        { letter: "P", name: "P", word: "Panda", english: "Panda", audio: "en_p.mp3", word_audio: "en_panda.mp3" },
        { letter: "Q", name: "Q", word: "Queen", english: "Queen", audio: "en_q.mp3", word_audio: "en_queen.mp3" },
        { letter: "R", name: "R", word: "Rabbit", english: "Rabbit", audio: "en_r.mp3", word_audio: "en_rabbit.mp3" },
        { letter: "S", name: "S", word: "Sun", english: "Sun", audio: "en_s.mp3", word_audio: "en_sun.mp3" },
        { letter: "T", name: "T", word: "Tiger", english: "Tiger", audio: "en_t.mp3", word_audio: "en_tiger.mp3" },
        { letter: "U", name: "U", word: "Umbrella", english: "Umbrella", audio: "en_u.mp3", word_audio: "en_umbrella.mp3" },
        { letter: "V", name: "V", word: "Van", english: "Van", audio: "en_v.mp3", word_audio: "en_van.mp3" },
        { letter: "W", name: "W", word: "Whale", english: "Whale", audio: "en_w.mp3", word_audio: "en_whale.mp3" },
        { letter: "X", name: "X", word: "Xylophone", english: "Xylophone", audio: "en_x.mp3", word_audio: "en_xylophone.mp3" },
        { letter: "Y", name: "Y", word: "Yo-yo", english: "Yo-yo", audio: "en_y.mp3", word_audio: "en_yoyo.mp3" },
        { letter: "Z", name: "Z", word: "Zebra", english: "Zebra", audio: "en_z.mp3", word_audio: "en_zebra.mp3" }
    ],
    arabic: [
        { letter: "أ", name: "Alif", word: "أرنب", audio: "ar_alif.mp3", word_audio: "ar_arnab.mp3" },
        { letter: "ب", name: "Ba", word: "بطة", audio: "ar_ba.mp3", word_audio: "ar_batta.mp3" },
        { letter: "ت", name: "Ta", word: "تفاح", audio: "ar_ta.mp3", word_audio: "ar_tuffah.mp3" },
        { letter: "ث", name: "Tha", word: "ثعلب", audio: "ar_tha.mp3", word_audio: "ar_thalab.mp3" },
        { letter: "ج", name: "Jim", word: "جمل", audio: "ar_jim.mp3", word_audio: "ar_jamal.mp3" },
        { letter: "ح", name: "Ha", word: "حوت", audio: "ar_ha.mp3", word_audio: "ar_hoot.mp3" },
        { letter: "خ", name: "Kha", word: "خروف", audio: "ar_kha.mp3", word_audio: "ar_kharoof.mp3" },
        { letter: "د", name: "Dal", word: "دب", audio: "ar_dal.mp3", word_audio: "ar_dub.mp3" },
        { letter: "ذ", name: "Thal", word: "ذئب", audio: "ar_thal.mp3", word_audio: "ar_theeb.mp3" },
        { letter: "ر", name: "Ra", word: "رمان", audio: "ar_ra.mp3", word_audio: "ar_ruman.mp3" },
        { letter: "ز", name: "Zay", word: "زرافة", audio: "ar_zay.mp3", word_audio: "ar_zarafa.mp3" },
        { letter: "س", name: "Sin", word: "سمكة", audio: "ar_sin.mp3", word_audio: "ar_samaka.mp3" },
        { letter: "ش", name: "Shin", word: "شمس", audio: "ar_shin.mp3", word_audio: "ar_shams.mp3" },
        { letter: "ص", name: "Sad", word: "صقر", audio: "ar_sad.mp3", word_audio: "ar_saqr.mp3" },
        { letter: "ض", name: "Dad", word: "ضفدع", audio: "ar_dad.mp3", word_audio: "ar_difda.mp3" },
        { letter: "ط", name: "Ta", word: "طائرة", audio: "ar_ta_heavy.mp3", word_audio: "ar_taira.mp3" },
        { letter: "ظ", name: "Za", word: "ظرف", audio: "ar_za_heavy.mp3", word_audio: "ar_zarf.mp3" },
        { letter: "ع", name: "Ain", word: "عين", audio: "ar_ain.mp3", word_audio: "ar_ain_word.mp3" },
        { letter: "غ", name: "Ghain", word: "غزال", audio: "ar_ghain.mp3", word_audio: "ar_ghazal.mp3" },
        { letter: "ف", name: "Fa", word: "فيل", audio: "ar_fa.mp3", word_audio: "ar_feel.mp3" },
        { letter: "ق", name: "Qaf", word: "قرد", audio: "ar_qaf.mp3", word_audio: "ar_qird.mp3" },
        { letter: "ك", name: "Kaf", word: "كلب", audio: "ar_kaf.mp3", word_audio: "ar_kalb.mp3" },
        { letter: "ل", name: "Lam", word: "ليمون", audio: "ar_lam.mp3", word_audio: "ar_laymoon.mp3" },
        { letter: "م", name: "Mim", word: "موز", audio: "ar_mim.mp3", word_audio: "ar_moaz.mp3" },
        { letter: "ن", name: "Nun", word: "نحلة", audio: "ar_nun.mp3", word_audio: "ar_nahla.mp3" },
        { letter: "ه", name: "Ha", word: "هلال", audio: "ar_ha_light.mp3", word_audio: "ar_hilal.mp3" },
        { letter: "و", name: "Waw", word: "وردة", audio: "ar_waw.mp3", word_audio: "ar_warda.mp3" },
        { letter: "ي", name: "Ya", word: "يد", audio: "ar_ya.mp3", word_audio: "ar_yad.mp3" }
    ],
    engdhi: [
        { letter: "A", english: "Apple", dhivehi: "އާފަލު", audio: "en_a.mp3" },
        { letter: "B", english: "Ball", dhivehi: "ބޯޅަ", audio: "en_b.mp3" },
        { letter: "C", english: "Cat", dhivehi: "ބުޅާ", audio: "en_c.mp3" },
        { letter: "D", english: "Dog", dhivehi: "ކުއްތާ", audio: "en_d.mp3" },
        { letter: "E", english: "Elephant", dhivehi: "އެތް", audio: "en_e.mp3" },
        { letter: "F", english: "Fish", dhivehi: "މަސް", audio: "en_f.mp3" },
        { letter: "G", english: "Giraffe", dhivehi: "ޒަރާފާ", audio: "en_g.mp3" },
        { letter: "H", english: "Horse", dhivehi: "އަސް", audio: "en_h.mp3" },
        { letter: "I", english: "Igloo", dhivehi: "އިގްލޫ", audio: "en_i.mp3" },
        { letter: "J", english: "Jelly", dhivehi: "ޖެލީ", audio: "en_j.mp3" },
        { letter: "K", english: "Kite", dhivehi: "ވަައިގުޑި", audio: "en_k.mp3" },
        { letter: "L", english: "Lion", dhivehi: "ސިންގާ", audio: "en_l.mp3" },
        { letter: "M", english: "Monkey", dhivehi: "ރިލް", audio: "en_m.mp3" },
        { letter: "N", english: "Net", dhivehi: "ދާ", audio: "en_n.mp3" },
        { letter: "O", english: "Orange", dhivehi: "އޮރެންޖް", audio: "en_o.mp3" },
        { letter: "P", english: "Panda", dhivehi: "ޕަންޑާ", audio: "en_p.mp3" },
        { letter: "Q", english: "Queen", dhivehi: "ރަނިކަމަނާ", audio: "en_q.mp3" },
        { letter: "R", english: "Rabbit", dhivehi: "މުސަޅު", audio: "en_r.mp3" },
        { letter: "S", english: "Sun", dhivehi: "އިރު", audio: "en_s.mp3" },
        { letter: "T", english: "Tiger", dhivehi: "މިނިކާވަގު", audio: "en_t.mp3" }
    ],
    numbers: [
        { letter: "1", english: "One", dhivehi: "އެކެއް", name: "1", audio: "num_1.mp3" },
        { letter: "2", english: "Two", dhivehi: "ދޭއް", name: "2", audio: "num_2.mp3" },
        { letter: "3", english: "Three", dhivehi: "ތިނެއް", name: "3", audio: "num_3.mp3" },
        { letter: "4", english: "Four", dhivehi: "ހަތަރެއް", name: "4", audio: "num_4.mp3" },
        { letter: "5", english: "Five", dhivehi: "ފަހެއް", name: "5", audio: "num_5.mp3" },
        { letter: "6", english: "Six", dhivehi: "ހަޔެއް", name: "6", audio: "num_6.mp3" },
        { letter: "7", english: "Seven", dhivehi: "ހަތެއް", name: "7", audio: "num_7.mp3" },
        { letter: "8", english: "Eight", dhivehi: "އަށެއް", name: "8", audio: "num_8.mp3" },
        { letter: "9", english: "Nine", dhivehi: "ނުވައެއް", name: "9", audio: "num_9.mp3" },
        { letter: "10", english: "Ten", dhivehi: "ދިހައެއް", name: "10", audio: "num_10.mp3" },
        { letter: "11", english: "Eleven", dhivehi: "އެގާރަ", name: "11", audio: "num_11.mp3" },
        { letter: "12", english: "Twelve", dhivehi: "ބާރަ", name: "12", audio: "num_12.mp3" },
        { letter: "13", english: "Thirteen", dhivehi: "ތޭރަ", name: "13", audio: "num_13.mp3" },
        { letter: "14", english: "Fourteen", dhivehi: "ސާދަ", name: "14", audio: "num_14.mp3" },
        { letter: "15", english: "Fifteen", dhivehi: "ފަނަރަ", name: "15", audio: "num_15.mp3" },
        { letter: "16", english: "Sixteen", dhivehi: "ސޯޅަ", name: "16", audio: "num_16.mp3" },
        { letter: "17", english: "Seventeen", dhivehi: "ސަތާރަ", name: "17", audio: "num_17.mp3" },
        { letter: "18", english: "Eighteen", dhivehi: "އަށާރަ", name: "18", audio: "num_18.mp3" },
        { letter: "19", english: "Nineteen", dhivehi: "ނަވާރަ", name: "19", audio: "num_19.mp3" },
        { letter: "20", english: "Twenty", dhivehi: "ވިހި", name: "20", audio: "num_20.mp3" }
    ]
};

const filiData = [
    { mark: "ަ", name: "އަބަފިލި", audio: "abafili.mp3" },
    { mark: "ި", name: "އިބިފިލި", audio: "ibifili.mp3" },
    { mark: "ު", name: "އުބުފިލި", audio: "ubufili.mp3" },
    { mark: "ާ", name: "އާފިލި", audio: "aafili.mp3" },
    { mark: "ީ", name: "އީފިލި", audio: "eefili.mp3" },
    { mark: "ޫ", name: "އޫފިލި", audio: "oofili.mp3" },
    { mark: "ެ", name: "އެބެފިލި", audio: "ebefili.mp3" },
    { mark: "ޭ", name: "އޭފިލި", audio: "eefili_long.mp3" },
    { mark: "ޮ", name: "އޮބޮފިލި", audio: "obofili.mp3" },
    { mark: "ޯ", name: "އޯފިލި", audio: "oofili_long.mp3" },
    { mark: "ް", name: "ސުކުން", audio: "sukun.mp3" }
];

const badges = [
    { id: 1,  name: "First Step",       icon: "🌱", how: "Complete your very first activity in the app!" },
    { id: 2,  name: "Tracer Pro",       icon: "✏️", how: "Trace 5 letters with 65%+ accuracy." },
    { id: 3,  name: "Quiz Master",      icon: "⭐", how: "Answer 10 quiz questions correctly." },
    { id: 4,  name: "Word Explorer",    icon: "🖼️", how: "Listen to 10 word sounds in the Words tab." },
    { id: 5,  name: "Dhivehi Fan",      icon: "🇲🇻", how: "Complete 20 activities in Dhivehi mode." },
    { id: 6,  name: "English Scholar",  icon: "🇬🇧", how: "Complete 10 activities in English mode." },
    { id: 7,  name: "Arabic Learner",   icon: "🇸🇦", how: "Complete 10 activities in Arabic mode." },
    { id: 8,  name: "Early Bird",       icon: "🌅", how: "Log in and complete an activity before 9 AM." },
    { id: 9,  name: "Night Owl",        icon: "🦉", how: "Complete an activity after 8 PM." },
    { id: 10, name: "Speedy Tracer",    icon: "🏎️", how: "Trace a letter with 90%+ accuracy on first try." },
    { id: 11, name: "Perfect Quiz",     icon: "💯", how: "Get 5 quiz questions correct in a row." },
    { id: 12, name: "Coloring Artist",  icon: "🎨", how: "Use 5 different colours in the tracing canvas." },
    { id: 13, name: "Fili Expert",      icon: "✨", how: "Listen to all vowel sounds in the Fili tab." },
    { id: 14, name: "Object Hunter",    icon: "🔍", how: "Click on 15 word cards in the Words tab." },
    { id: 15, name: "Mystery Solver",   icon: "🎁", how: "Open the Mystery Box by completing daily tasks." },
    { id: 16, name: "Super Student",    icon: "👔", how: "Earn 100 points in total." },
    { id: 17, name: "Happy Learner",    icon: "😊", how: "Complete activities on 3 different days." },
    { id: 18, name: "Knowledge King",   icon: "👑", how: "Earn 250 points in total." },
    { id: 19, name: "Alphabet Hero",    icon: "🦸", how: "Listen to every letter sound in the Letters tab." },
    { id: 20, name: "Brave Writer",     icon: "🗡️", how: "Trace 10 different letters." },
    { id: 21, name: "Silver Medal",     icon: "🥈", how: "Reach the top 10 in the Hall of Fame." },
    { id: 22, name: "Gold Medal",       icon: "🥇", how: "Reach the top 3 in the Hall of Fame." },
    { id: 23, name: "Diamond Badge",    icon: "💎", how: "Earn 500 points in total." },
    { id: 24, name: "Rocket Learner",   icon: "🚀", how: "Complete 5 activities in one day." },
    { id: 25, name: "Brain Power",      icon: "🧠", how: "Answer 25 quiz questions correctly." },
    { id: 26, name: "Daily Hero",       icon: "📅", how: "Complete all daily tasks in a single day." },
    { id: 27, name: "Star Student",     icon: "🌟", how: "Earn 1000 points in total." },
    { id: 28, name: "Magic Writer",     icon: "🪄", how: "Trace 20 letters successfully." },
    { id: 29, name: "Friend of Letters",icon: "🤝", how: "Click on every letter in the Letters tab at least once." },
    { id: 30, name: "Voice of Hub",     icon: "📣", how: "Listen to 30 different audio clips." },
    { id: 31, name: "Smart Cookie",     icon: "🍪", how: "Get 3 perfect traces in one session." },
    { id: 32, name: "Focus Finder",     icon: "🎯", how: "Complete 10 quiz questions without any wrong answers." },
    { id: 33, name: "Explorer Badge",   icon: "🧭", how: "Try all available tabs in the app." },
    { id: 34, name: "Winner Spirit",    icon: "🏆", how: "Earn 1500 points in total." },
    { id: 35, name: "Kind Heart",       icon: "❤️", how: "Log in for 5 days in a row." },
    { id: 36, name: "Fire Starter",     icon: "🔥", how: "Complete 10 activities in one session." },
    { id: 37, name: "Ice Cooler",       icon: "❄️", how: "Score 100% coverage on a tracing task." },
    { id: 38, name: "Sun Shiner",       icon: "☀️", how: "Earn 2000 points in total." },
    { id: 39, name: "Cloud Walker",     icon: "☁️", how: "Play the Dino Jump mystery game 3 times." },
    { id: 40, name: "Rainbow Maker",    icon: "🌈", how: "Use all 8 colours in the tracing canvas." },
    { id: 41, name: "Globe Trotter",    icon: "🌍", how: "Complete activities in 3 different languages." },
    { id: 42, name: "Music Lover",      icon: "🎵", how: "Listen to 50 audio clips total." },
    { id: 43, name: "Book Worm",        icon: "📖", how: "Complete 50 activities in total." },
    { id: 44, name: "Idea Spark",       icon: "💡", how: "Earn 3000 points in total." },
    { id: 45, name: "Team Player",      icon: "👨‍👩‍👧‍👦", how: "Create profiles for 2 or more kids." },
    { id: 46, name: "Peace Maker",      icon: "🕊️", how: "Earn 4000 points in total." },
    { id: 47, name: "Growth Mindset",   icon: "📈", how: "Improve your quiz score 3 times in a row." },
    { id: 48, name: "Infinite Wisdom",  icon: "♾️", how: "Earn 5000 points in total." },
    { id: 49, name: "Grand Champion",   icon: "🏅", how: "Reach #1 in the Hall of Fame." },
    { id: 50, name: "Ultimate Legend",  icon: "🦄", how: "Collect 49 other badges!" }
];

